# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
  - "2.7"
  - "3.7"

install:
  - "pip install ."

script:
# Run the Python unit tests
  - "python setup.py test"
# Run the example scripts
  - "cd examples/"
  - ./run_examples.sh
