[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "RnaChipIntegrator"
dynamic = [
  "version",
  "description",
  "readme",
  "license",
  "authors",
  "maintainers",
  "keywords",
  "classifiers",
  "scripts",
  "dependencies"
]
